apiVersion: apps/v1
kind: Deployment

metadata:
  name: gateway-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gateway-service

  template:
    metadata:
      labels:
        app: gateway-service

    spec:
      containers:
      - name: gateway-service
        image: gateway-service:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 3003

        env:
        - name: USER_SERVICE_URL
          value: "http://user-service:3000"

        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:3001"

        - name: ORDER_SERVICE_URL
          value: "http://order-service:3002"

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"

          limits:
            memory: "256Mi"
            cpu: "250m"

        livenessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5