services:

  user-service:
    build:
      context:  /root/Microservices-Task/Microservices/user-service
      dockerfile: /root/Microservices-Task/submission/user-service/Dockerfile
    container_name: user_service
    ports:
      - "3000:3000"
    networks:
      - microservice-net
    restart: unless-stopped

  product-service:
    build:
      context:  /root/Microservices-Task/Microservices/product-service
      dockerfile: /root/Microservices-Task/submission/product-service/Dockerfile
    container_name: product_service
    ports:
      - "3001:3001"
    networks:
      - microservice-net
    restart: unless-stopped

  order-service:
    build:
      context:  /root/Microservices-Task/Microservices/order-service
      dockerfile: /root/Microservices-Task/submission/order-service/Dockerfile
    container_name: order_service
    ports:
      - "3002:3002"
    networks:
      - microservice-net
    restart: unless-stopped

  gateway-service:
    build:
      context: /root/Microservices-Task/Microservices/gateway-service
      dockerfile: /root/Microservices-Task/submission/gateway-service/Dockerfile
    container_name: gateway_service
    ports:
      - "3003:3003"
    networks:
      - microservice-net
    environment:
      USER_SERVICE_URL: http://user-service:3000
      PRODUCT_SERVICE_URL: http://product-service:3001
      ORDER_SERVICE_URL: http://order-service:3002
    depends_on:
      - user-service
      - product-service
      - order-service
    restart: unless-stopped

networks:
  microservice-net:
    driver: bridge